import dotenv from "dotenv";

dotenv.config();

const {
  DATABASE_HOSTNAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_DBNAME,
  REDIS_HOST,
  REDIS_PORT 
} = process.env;

export default {
  DATABASE_HOSTNAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_DBNAME,
  REDIS_HOST,
  REDIS_PORT 
}